library(readr)
library(data.table)
# @param 
# actual is vector, pred is data.frame
# mlogloss(actual,pred)
mlogloss <- function(actual,pred){
	actual <- as.integer(as.factor(actual))
	probs <- rep(0,length(actual))
	for(i in 1:length(actual)) { probs[i] <- pred[i,actual[i]]}
	probs <- as.numeric(probs)
	probs[which(probs>1-1e-15)] <- 1-1e-15
	probs[which(probs<1e-15)] <- 1e-15
	return(-(1/length(actual))*sum(log(probs)))
}

path <- "../Data/"
raw_train <- fread(paste0(path,"train.csv"))
raw_train <- as.data.frame(raw_train)
trainId <- raw_train$id
#
xgb_train <- fread(paste0(path,"xgb_retrain.csv"))
xgb_train <- as.data.frame(xgb_train)
xgb_train$id <- NULL
colnames(xgb_train) <- gsub('Class_','',colnames(xgb_train))
colnames(xgb_train) <- paste0('xgb_',colnames(xgb_train))
rf_train <- fread(paste0(path,"rf_retrain.csv"))
rf_train <- as.data.frame(rf_train)
rf_train$id <- NULL
colnames(rf_train) <- gsub('Class_','',colnames(rf_train))
colnames(rf_train) <- paste0('rf_',colnames(rf_train))
ET_train <- fread(paste0(path,"extraTree_retrain.csv"))
ET_train <- as.data.frame(ET_train)
ET_train$id <- NULL
colnames(ET_train) <- gsub('Class_','',colnames(ET_train))
colnames(ET_train) <- paste0('ET_',colnames(ET_train))
svm_train <- fread(paste0(path,"svm_retrain.csv"))
svm_train <- as.data.frame(svm_train)
svm_train$id <- NULL
colnames(svm_train) <- gsub('Class_','',colnames(svm_train))
colnames(svm_train) <- paste0('svm_',colnames(svm_train))
NN4_train <- fread(paste0(path,"kerasNN4_retrain.csv"))
NN4_train <- as.data.frame(NN4_train)
NN4_train$id <- NULL
colnames(NN4_train) <- gsub('Class_','',colnames(NN4_train))
colnames(NN4_train) <- paste0('kerasNN4_',colnames(NN4_train))
NN3_train <- fread(paste0(path,"kerasNN3_retrain.csv"))
NN3_train <- as.data.frame(NN3_train)
NN3_train$id <- NULL
colnames(NN3_train) <- gsub('Class_','',colnames(NN3_train))
colnames(NN3_train) <- paste0('kerasNN3_',colnames(NN3_train))
NN2_train <- fread(paste0(path,"kerasNN2_retrain.csv"))
NN2_train <- as.data.frame(NN2_train)
NN2_train$id <- NULL
colnames(NN2_train) <- gsub('Class_','',colnames(NN2_train))
colnames(NN2_train) <- paste0('kerasNN2_',colnames(NN2_train))
knn1_train <- fread(paste0(path,"knn1_retrain.csv"))
knn1_train <- as.data.frame(knn1_train)
knn1_train$id <- NULL
colnames(knn1_train) <- gsub('Class_','',colnames(knn1_train))
colnames(knn1_train) <- paste0('knn1_',colnames(knn1_train))
knn2_train <- fread(paste0(path,"knn2_retrain.csv"))
knn2_train <- as.data.frame(knn2_train)
knn2_train$id <- NULL
colnames(knn2_train) <- gsub('Class_','',colnames(knn2_train))
colnames(knn2_train) <- paste0('knn2_',colnames(knn2_train))
knn3_train <- fread(paste0(path,"knn3_retrain.csv"))
knn3_train <- as.data.frame(knn3_train)
knn3_train$id <- NULL
colnames(knn3_train) <- gsub('Class_','',colnames(knn3_train))
colnames(knn3_train) <- paste0('knn3_',colnames(knn3_train))
knn4_train <- fread(paste0(path,"knn4_retrain.csv"))
knn4_train <- as.data.frame(knn4_train)
knn4_train$id <- NULL
colnames(knn4_train) <- gsub('Class_','',colnames(knn4_train))
colnames(knn4_train) <- paste0('knn4_',colnames(knn4_train))
knn5_train <- fread(paste0(path,"knn5_retrain.csv"))
knn5_train <- as.data.frame(knn5_train)
knn5_train$id <- NULL
colnames(knn5_train) <- gsub('Class_','',colnames(knn5_train))
colnames(knn5_train) <- paste0('knn5_',colnames(knn5_train))
knn6_train <- fread(paste0(path,"knn6_retrain.csv"))
knn6_train <- as.data.frame(knn6_train)
knn6_train$id <- NULL
colnames(knn6_train) <- gsub('Class_','',colnames(knn6_train))
colnames(knn6_train) <- paste0('knn6_',colnames(knn6_train))
knn7_train <- fread(paste0(path,"knn7_retrain.csv"))
knn7_train <- as.data.frame(knn7_train)
knn7_train$id <- NULL
colnames(knn7_train) <- gsub('Class_','',colnames(knn7_train))
colnames(knn7_train) <- paste0('knn7_',colnames(knn7_train))
knn8_train <- fread(paste0(path,"knn8_retrain.csv"))
knn8_train <- as.data.frame(knn8_train)
knn8_train$id <- NULL
colnames(knn8_train) <- gsub('Class_','',colnames(knn8_train))
colnames(knn8_train) <- paste0('knn8_',colnames(knn8_train))
knn9_train <- fread(paste0(path,"knn9_retrain.csv"))
knn9_train <- as.data.frame(knn9_train)
knn9_train$id <- NULL
colnames(knn9_train) <- gsub('Class_','',colnames(knn9_train))
colnames(knn9_train) <- paste0('knn9_',colnames(knn9_train))
knn10_train <- fread(paste0(path,"knn10_retrain.csv"))
knn10_train <- as.data.frame(knn10_train)
knn10_train$id <- NULL
colnames(knn10_train) <- gsub('Class_','',colnames(knn10_train))
colnames(knn10_train) <- paste0('knn10_',colnames(knn10_train))
knn11_train <- fread(paste0(path,"knn11_retrain.csv"))
knn11_train <- as.data.frame(knn11_train)
knn11_train$id <- NULL
colnames(knn11_train) <- gsub('Class_','',colnames(knn11_train))
colnames(knn11_train) <- paste0('knn11_',colnames(knn11_train))

# tfidf space
xgb_tfidf_train <- fread(paste0(path,"xgb_tfidf_retrain.csv"))
xgb_tfidf_train <- as.data.frame(xgb_tfidf_train)
xgb_tfidf_train$id <- NULL
colnames(xgb_tfidf_train) <- gsub('Class_','',colnames(xgb_tfidf_train))
colnames(xgb_tfidf_train) <- paste0('xgb_tfidf_',colnames(xgb_tfidf_train))
rf_tfidf_train <- fread(paste0(path,"rf_tfidf_retrain.csv"))
rf_tfidf_train <- as.data.frame(rf_tfidf_train)
rf_tfidf_train$id <- NULL
colnames(rf_tfidf_train) <- gsub('Class_','',colnames(rf_tfidf_train))
colnames(rf_tfidf_train) <- paste0('rf_tfidf_',colnames(rf_tfidf_train))
ET_tfidf_train <- fread(paste0(path,"extraTree_tfidf_retrain.csv"))
ET_tfidf_train <- as.data.frame(ET_tfidf_train)
ET_tfidf_train$id <- NULL
colnames(ET_tfidf_train) <- gsub('Class_','',colnames(ET_tfidf_train))
colnames(ET_tfidf_train) <- paste0('ET_tfidf_',colnames(ET_tfidf_train))
svm_tfidf_train <- fread(paste0(path,"svm_tfidf_retrain.csv"))
svm_tfidf_train <- as.data.frame(svm_tfidf_train)
svm_tfidf_train$id <- NULL
colnames(svm_tfidf_train) <- gsub('Class_','',colnames(svm_tfidf_train))
colnames(svm_tfidf_train) <- paste0('svm_tfidf_',colnames(svm_tfidf_train))
NN4_tfidf_train <- fread(paste0(path,"kerasNN4_tfidf_retrain.csv"))
NN4_tfidf_train <- as.data.frame(NN4_tfidf_train)
NN4_tfidf_train$id <- NULL
colnames(NN4_tfidf_train) <- gsub('Class_','',colnames(NN4_tfidf_train))
colnames(NN4_tfidf_train) <- paste0('kerasNN4_tfidf_',colnames(NN4_tfidf_train))
NN3_tfidf_train <- fread(paste0(path,"kerasNN3_tfidf_retrain.csv"))
NN3_tfidf_train <- as.data.frame(NN3_tfidf_train)
NN3_tfidf_train$id <- NULL
colnames(NN3_tfidf_train) <- gsub('Class_','',colnames(NN3_tfidf_train))
colnames(NN3_tfidf_train) <- paste0('kerasNN3_tfidf_',colnames(NN3_tfidf_train))
NN2_tfidf_train <- fread(paste0(path,"kerasNN2_tfidf_retrain.csv"))
NN2_tfidf_train <- as.data.frame(NN2_tfidf_train)
NN2_tfidf_train$id <- NULL
colnames(NN2_tfidf_train) <- gsub('Class_','',colnames(NN2_tfidf_train))
colnames(NN2_tfidf_train) <- paste0('kerasNN2_tfidf_',colnames(NN2_tfidf_train))
knn1_tfidf_train <- fread(paste0(path,"knn1_tfidf_retrain.csv"))
knn1_tfidf_train <- as.data.frame(knn1_tfidf_train)
knn1_tfidf_train$id <- NULL
colnames(knn1_tfidf_train) <- gsub('Class_','',colnames(knn1_tfidf_train))
colnames(knn1_tfidf_train) <- paste0('knn1_tfidf_',colnames(knn1_tfidf_train))
knn2_tfidf_train <- fread(paste0(path,"knn2_tfidf_retrain.csv"))
knn2_tfidf_train <- as.data.frame(knn2_tfidf_train)
knn2_tfidf_train$id <- NULL
colnames(knn2_tfidf_train) <- gsub('Class_','',colnames(knn2_tfidf_train))
colnames(knn2_tfidf_train) <- paste0('knn2_tfidf_',colnames(knn2_tfidf_train))
knn3_tfidf_train <- fread(paste0(path,"knn3_tfidf_retrain.csv"))
knn3_tfidf_train <- as.data.frame(knn3_tfidf_train)
knn3_tfidf_train$id <- NULL
colnames(knn3_tfidf_train) <- gsub('Class_','',colnames(knn3_tfidf_train))
colnames(knn3_tfidf_train) <- paste0('knn3_tfidf_',colnames(knn3_tfidf_train))
knn4_tfidf_train <- fread(paste0(path,"knn4_tfidf_retrain.csv"))
knn4_tfidf_train <- as.data.frame(knn4_tfidf_train)
knn4_tfidf_train$id <- NULL
colnames(knn4_tfidf_train) <- gsub('Class_','',colnames(knn4_tfidf_train))
colnames(knn4_tfidf_train) <- paste0('knn4_tfidf_',colnames(knn4_tfidf_train))
knn5_tfidf_train <- fread(paste0(path,"knn5_tfidf_retrain.csv"))
knn5_tfidf_train <- as.data.frame(knn5_tfidf_train)
knn5_tfidf_train$id <- NULL
colnames(knn5_tfidf_train) <- gsub('Class_','',colnames(knn5_tfidf_train))
colnames(knn5_tfidf_train) <- paste0('knn5_tfidf_',colnames(knn5_tfidf_train))
knn6_tfidf_train <- fread(paste0(path,"knn6_tfidf_retrain.csv"))
knn6_tfidf_train <- as.data.frame(knn6_tfidf_train)
knn6_tfidf_train$id <- NULL
colnames(knn6_tfidf_train) <- gsub('Class_','',colnames(knn6_tfidf_train))
colnames(knn6_tfidf_train) <- paste0('knn6_tfidf_',colnames(knn6_tfidf_train))
knn7_tfidf_train <- fread(paste0(path,"knn7_tfidf_retrain.csv"))
knn7_tfidf_train <- as.data.frame(knn7_tfidf_train)
knn7_tfidf_train$id <- NULL
colnames(knn7_tfidf_train) <- gsub('Class_','',colnames(knn7_tfidf_train))
colnames(knn7_tfidf_train) <- paste0('knn7_tfidf_',colnames(knn7_tfidf_train))
knn8_tfidf_train <- fread(paste0(path,"knn8_tfidf_retrain.csv"))
knn8_tfidf_train <- as.data.frame(knn8_tfidf_train)
knn8_tfidf_train$id <- NULL
colnames(knn8_tfidf_train) <- gsub('Class_','',colnames(knn8_tfidf_train))
colnames(knn8_tfidf_train) <- paste0('knn8_tfidf_',colnames(knn8_tfidf_train))
knn9_tfidf_train <- fread(paste0(path,"knn9_tfidf_retrain.csv"))
knn9_tfidf_train <- as.data.frame(knn9_tfidf_train)
knn9_tfidf_train$id <- NULL
colnames(knn9_tfidf_train) <- gsub('Class_','',colnames(knn9_tfidf_train))
colnames(knn9_tfidf_train) <- paste0('knn9_tfidf_',colnames(knn9_tfidf_train))
knn10_tfidf_train <- fread(paste0(path,"knn10_tfidf_retrain.csv"))
knn10_tfidf_train <- as.data.frame(knn10_tfidf_train)
knn10_tfidf_train$id <- NULL
colnames(knn10_tfidf_train) <- gsub('Class_','',colnames(knn10_tfidf_train))
colnames(knn10_tfidf_train) <- paste0('knn10_tfidf_',colnames(knn10_tfidf_train))
knn11_tfidf_train <- fread(paste0(path,"knn11_tfidf_retrain.csv"))
knn11_tfidf_train <- as.data.frame(knn11_tfidf_train)
knn11_tfidf_train$id <- NULL
colnames(knn11_tfidf_train) <- gsub('Class_','',colnames(knn11_tfidf_train))
colnames(knn11_tfidf_train) <- paste0('knn11_tfidf_',colnames(knn11_tfidf_train))

train <- cbind(target=raw_train$target,xgb_train)
train <- cbind(train,rf_train)
train <- cbind(train,ET_train)
train <- cbind(train,svm_train)
train <- cbind(train,NN4_train)
train <- cbind(train,NN3_train)
train <- cbind(train,NN2_train)
train <- cbind(train,knn1_train)
train <- cbind(train,knn2_train)
train <- cbind(train,knn3_train)
train <- cbind(train,knn4_train)
train <- cbind(train,knn5_train)
train <- cbind(train,knn6_train)
train <- cbind(train,knn7_train)
train <- cbind(train,knn8_train)
train <- cbind(train,knn9_train)
train <- cbind(train,knn10_train)
train <- cbind(train,knn11_train)
train <- cbind(train,xgb_tfidf_train)
train <- cbind(train,rf_tfidf_train)
train <- cbind(train,ET_tfidf_train)
train <- cbind(train,svm_tfidf_train)
train <- cbind(train,NN4_tfidf_train)
train <- cbind(train,NN3_tfidf_train)
train <- cbind(train,NN2_tfidf_train)
train <- cbind(train,knn1_tfidf_train)
train <- cbind(train,knn2_tfidf_train)
train <- cbind(train,knn3_tfidf_train)
train <- cbind(train,knn4_tfidf_train)
train <- cbind(train,knn5_tfidf_train)
train <- cbind(train,knn6_tfidf_train)
train <- cbind(train,knn7_tfidf_train)
train <- cbind(train,knn8_tfidf_train)
train <- cbind(train,knn9_tfidf_train)
train <- cbind(train,knn10_tfidf_train)
train <- cbind(train,knn11_tfidf_train)

tmp <- train$target
train$target <- NULL
train$target <- tmp

train <- cbind(id=trainId,train)
for(i in 1:ncol(train)) { train[,i] <- as.character(train[,i])}
write_csv(train,paste0(path,"train_2nd.csv"))


# make test data
raw_test <- fread(paste0(path,"test.csv"))
raw_test <- as.data.frame(raw_test)
id <- raw_test$id
#
xgb_test <- fread(paste0(path,"xgb.csv"))
xgb_test <- as.data.frame(xgb_test)
xgb_test$id <- NULL
colnames(xgb_test) <- gsub('Class_','',colnames(xgb_test))
colnames(xgb_test) <- paste0('xgb_',colnames(xgb_test))
rf_test <- fread(paste0(path,"rf.csv"))
rf_test <- as.data.frame(rf_test)
rf_test$id <- NULL
colnames(rf_test) <- gsub('Class_','',colnames(rf_test))
colnames(rf_test) <- paste0('rf_',colnames(rf_test))
ET_test <- fread(paste0(path,"extraTree.csv"))
ET_test <- as.data.frame(ET_test)
ET_test$id <- NULL
colnames(ET_test) <- gsub('Class_','',colnames(ET_test))
colnames(ET_test) <- paste0('ET_',colnames(ET_test))
svm_test <- fread(paste0(path,"svm.csv"))
svm_test <- as.data.frame(svm_test)
svm_test$id <- NULL
colnames(svm_test) <- gsub('Class_','',colnames(svm_test))
colnames(svm_test) <- paste0('svm_',colnames(svm_test))
NN4_test <- fread(paste0(path,"kerasNN4.csv"))
NN4_test <- as.data.frame(NN4_test)
NN4_test$id <- NULL
colnames(NN4_test) <- gsub('Class_','',colnames(NN4_test))
colnames(NN4_test) <- paste0('kerasNN4_',colnames(NN4_test))
NN3_test <- fread(paste0(path,"kerasNN3.csv"))
NN3_test <- as.data.frame(NN3_test)
NN3_test$id <- NULL
colnames(NN3_test) <- gsub('Class_','',colnames(NN3_test))
colnames(NN3_test) <- paste0('kerasNN3_',colnames(NN3_test))
NN2_test <- fread(paste0(path,"kerasNN2.csv"))
NN2_test <- as.data.frame(NN2_test)
NN2_test$id <- NULL
colnames(NN2_test) <- gsub('Class_','',colnames(NN2_test))
colnames(NN2_test) <- paste0('kerasNN2_',colnames(NN2_test))
knn1_test <- fread(paste0(path,"knn1.csv"))
knn1_test <- as.data.frame(knn1_test)
knn1_test$id <- NULL
colnames(knn1_test) <- gsub('Class_','',colnames(knn1_test))
colnames(knn1_test) <- paste0('knn1_',colnames(knn1_test))
knn2_test <- fread(paste0(path,"knn2.csv"))
knn2_test <- as.data.frame(knn2_test)
knn2_test$id <- NULL
colnames(knn2_test) <- gsub('Class_','',colnames(knn2_test))
colnames(knn2_test) <- paste0('knn2_',colnames(knn2_test))
knn3_test <- fread(paste0(path,"knn3.csv"))
knn3_test <- as.data.frame(knn3_test)
knn3_test$id <- NULL
colnames(knn3_test) <- gsub('Class_','',colnames(knn3_test))
colnames(knn3_test) <- paste0('knn3_',colnames(knn3_test))
knn4_test <- fread(paste0(path,"knn4.csv"))
knn4_test <- as.data.frame(knn4_test)
knn4_test$id <- NULL
colnames(knn4_test) <- gsub('Class_','',colnames(knn4_test))
colnames(knn4_test) <- paste0('knn4_',colnames(knn4_test))
knn5_test <- fread(paste0(path,"knn5.csv"))
knn5_test <- as.data.frame(knn5_test)
knn5_test$id <- NULL
colnames(knn5_test) <- gsub('Class_','',colnames(knn5_test))
colnames(knn5_test) <- paste0('knn5_',colnames(knn5_test))
knn6_test <- fread(paste0(path,"knn6.csv"))
knn6_test <- as.data.frame(knn6_test)
knn6_test$id <- NULL
colnames(knn6_test) <- gsub('Class_','',colnames(knn6_test))
colnames(knn6_test) <- paste0('knn6_',colnames(knn6_test))
knn7_test <- fread(paste0(path,"knn7.csv"))
knn7_test <- as.data.frame(knn7_test)
knn7_test$id <- NULL
colnames(knn7_test) <- gsub('Class_','',colnames(knn7_test))
colnames(knn7_test) <- paste0('knn7_',colnames(knn7_test))
knn8_test <- fread(paste0(path,"knn8.csv"))
knn8_test <- as.data.frame(knn8_test)
knn8_test$id <- NULL
colnames(knn8_test) <- gsub('Class_','',colnames(knn8_test))
colnames(knn8_test) <- paste0('knn8_',colnames(knn8_test))
knn9_test <- fread(paste0(path,"knn9.csv"))
knn9_test <- as.data.frame(knn9_test)
knn9_test$id <- NULL
colnames(knn9_test) <- gsub('Class_','',colnames(knn9_test))
colnames(knn9_test) <- paste0('knn9_',colnames(knn9_test))
knn10_test <- fread(paste0(path,"knn10.csv"))
knn10_test <- as.data.frame(knn10_test)
knn10_test$id <- NULL
colnames(knn10_test) <- gsub('Class_','',colnames(knn10_test))
colnames(knn10_test) <- paste0('knn10_',colnames(knn10_test))
knn11_test <- fread(paste0(path,"knn11.csv"))
knn11_test <- as.data.frame(knn11_test)
knn11_test$id <- NULL
colnames(knn11_test) <- gsub('Class_','',colnames(knn11_test))
colnames(knn11_test) <- paste0('knn11_',colnames(knn11_test))

# tfidf space 
xgb_tfidf_test <- fread(paste0(path,"xgb_tfidf.csv"))
xgb_tfidf_test <- as.data.frame(xgb_tfidf_test)
xgb_tfidf_test$id <- NULL
colnames(xgb_tfidf_test) <- gsub('Class_','',colnames(xgb_tfidf_test))
colnames(xgb_tfidf_test) <- paste0('xgb_tfidf_',colnames(xgb_tfidf_test))
rf_tfidf_test <- fread(paste0(path,"rf_tfidf.csv"))
rf_tfidf_test <- as.data.frame(rf_tfidf_test)
rf_tfidf_test$id <- NULL
colnames(rf_tfidf_test) <- gsub('Class_','',colnames(rf_tfidf_test))
colnames(rf_tfidf_test) <- paste0('rf_tfidf_',colnames(rf_tfidf_test))
ET_tfidf_test <- fread(paste0(path,"extraTree_tfidf.csv"))
ET_tfidf_test <- as.data.frame(ET_tfidf_test)
ET_tfidf_test$id <- NULL
colnames(ET_tfidf_test) <- gsub('Class_','',colnames(ET_tfidf_test))
colnames(ET_tfidf_test) <- paste0('ET_tfidf_',colnames(ET_tfidf_test))
svm_tfidf_test <- fread(paste0(path,"svm_tfidf.csv"))
svm_tfidf_test <- as.data.frame(svm_tfidf_test)
svm_tfidf_test$id <- NULL
colnames(svm_tfidf_test) <- gsub('Class_','',colnames(svm_tfidf_test))
colnames(svm_tfidf_test) <- paste0('svm_tfidf_',colnames(svm_tfidf_test))
NN4_tfidf_test <- fread(paste0(path,"kerasNN4_tfidf.csv"))
NN4_tfidf_test <- as.data.frame(NN4_tfidf_test)
NN4_tfidf_test$id <- NULL
colnames(NN4_tfidf_test) <- gsub('Class_','',colnames(NN4_tfidf_test))
colnames(NN4_tfidf_test) <- paste0('kerasNN4_tfidf_',colnames(NN4_tfidf_test))
NN3_tfidf_test <- fread(paste0(path,"kerasNN3_tfidf.csv"))
NN3_tfidf_test <- as.data.frame(NN3_tfidf_test)
NN3_tfidf_test$id <- NULL
colnames(NN3_tfidf_test) <- gsub('Class_','',colnames(NN3_tfidf_test))
colnames(NN3_tfidf_test) <- paste0('kerasNN3_tfidf_',colnames(NN3_tfidf_test))
NN2_tfidf_test <- fread(paste0(path,"kerasNN2_tfidf.csv"))
NN2_tfidf_test <- as.data.frame(NN2_tfidf_test)
NN2_tfidf_test$id <- NULL
colnames(NN2_tfidf_test) <- gsub('Class_','',colnames(NN2_tfidf_test))
colnames(NN2_tfidf_test) <- paste0('kerasNN2_tfidf_',colnames(NN2_tfidf_test))
knn1_tfidf_test <- fread(paste0(path,"knn1_tfidf.csv"))
knn1_tfidf_test <- as.data.frame(knn1_tfidf_test)
knn1_tfidf_test$id <- NULL
colnames(knn1_tfidf_test) <- gsub('Class_','',colnames(knn1_tfidf_test))
colnames(knn1_tfidf_test) <- paste0('knn1_tfidf_',colnames(knn1_tfidf_test))
knn2_tfidf_test <- fread(paste0(path,"knn2_tfidf.csv"))
knn2_tfidf_test <- as.data.frame(knn2_tfidf_test)
knn2_tfidf_test$id <- NULL
colnames(knn2_tfidf_test) <- gsub('Class_','',colnames(knn2_tfidf_test))
colnames(knn2_tfidf_test) <- paste0('knn2_tfidf_',colnames(knn2_tfidf_test))
knn3_tfidf_test <- fread(paste0(path,"knn3_tfidf.csv"))
knn3_tfidf_test <- as.data.frame(knn3_tfidf_test)
knn3_tfidf_test$id <- NULL
colnames(knn3_tfidf_test) <- gsub('Class_','',colnames(knn3_tfidf_test))
colnames(knn3_tfidf_test) <- paste0('knn3_tfidf_',colnames(knn3_tfidf_test))
knn4_tfidf_test <- fread(paste0(path,"knn4_tfidf.csv"))
knn4_tfidf_test <- as.data.frame(knn4_tfidf_test)
knn4_tfidf_test$id <- NULL
colnames(knn4_tfidf_test) <- gsub('Class_','',colnames(knn4_tfidf_test))
colnames(knn4_tfidf_test) <- paste0('knn4_tfidf_',colnames(knn4_tfidf_test))
knn5_tfidf_test <- fread(paste0(path,"knn5_tfidf.csv"))
knn5_tfidf_test <- as.data.frame(knn5_tfidf_test)
knn5_tfidf_test$id <- NULL
colnames(knn5_tfidf_test) <- gsub('Class_','',colnames(knn5_tfidf_test))
colnames(knn5_tfidf_test) <- paste0('knn5_tfidf_',colnames(knn5_tfidf_test))
knn6_tfidf_test <- fread(paste0(path,"knn6_tfidf.csv"))
knn6_tfidf_test <- as.data.frame(knn6_tfidf_test)
knn6_tfidf_test$id <- NULL
colnames(knn6_tfidf_test) <- gsub('Class_','',colnames(knn6_tfidf_test))
colnames(knn6_tfidf_test) <- paste0('knn6_tfidf_',colnames(knn6_tfidf_test))
knn7_tfidf_test <- fread(paste0(path,"knn7_tfidf.csv"))
knn7_tfidf_test <- as.data.frame(knn7_tfidf_test)
knn7_tfidf_test$id <- NULL
colnames(knn7_tfidf_test) <- gsub('Class_','',colnames(knn7_tfidf_test))
colnames(knn7_tfidf_test) <- paste0('knn7_tfidf_',colnames(knn7_tfidf_test))
knn8_tfidf_test <- fread(paste0(path,"knn8_tfidf.csv"))
knn8_tfidf_test <- as.data.frame(knn8_tfidf_test)
knn8_tfidf_test$id <- NULL
colnames(knn8_tfidf_test) <- gsub('Class_','',colnames(knn8_tfidf_test))
colnames(knn8_tfidf_test) <- paste0('knn8_tfidf_',colnames(knn8_tfidf_test))
knn9_tfidf_test <- fread(paste0(path,"knn9_tfidf.csv"))
knn9_tfidf_test <- as.data.frame(knn9_tfidf_test)
knn9_tfidf_test$id <- NULL
colnames(knn9_tfidf_test) <- gsub('Class_','',colnames(knn9_tfidf_test))
colnames(knn9_tfidf_test) <- paste0('knn9_tfidf_',colnames(knn9_tfidf_test))
knn10_tfidf_test <- fread(paste0(path,"knn10_tfidf.csv"))
knn10_tfidf_test <- as.data.frame(knn10_tfidf_test)
knn10_tfidf_test$id <- NULL
colnames(knn10_tfidf_test) <- gsub('Class_','',colnames(knn10_tfidf_test))
colnames(knn10_tfidf_test) <- paste0('knn10_tfidf_',colnames(knn10_tfidf_test))
knn11_tfidf_test <- fread(paste0(path,"knn11_tfidf.csv"))
knn11_tfidf_test <- as.data.frame(knn11_tfidf_test)
knn11_tfidf_test$id <- NULL
colnames(knn11_tfidf_test) <- gsub('Class_','',colnames(knn11_tfidf_test))
colnames(knn11_tfidf_test) <- paste0('knn11_tfidf_',colnames(knn11_tfidf_test))

test <- cbind(xgb_test,rf_test)
test <- cbind(test,ET_test)
test <- cbind(test,svm_test)
test <- cbind(test,NN4_test)
test <- cbind(test,NN3_test)
test <- cbind(test,NN2_test)
test <- cbind(test,knn1_test)
test <- cbind(test,knn2_test)
test <- cbind(test,knn3_test)
test <- cbind(test,knn4_test)
test <- cbind(test,knn5_test)
test <- cbind(test,knn6_test)
test <- cbind(test,knn7_test)
test <- cbind(test,knn8_test)
test <- cbind(test,knn9_test)
test <- cbind(test,knn10_test)
test <- cbind(test,knn11_test)
test <- cbind(test,xgb_tfidf_test)
test <- cbind(test,rf_tfidf_test)
test <- cbind(test,ET_tfidf_test)
test <- cbind(test,svm_tfidf_test)
test <- cbind(test,NN4_tfidf_test)
test <- cbind(test,NN3_tfidf_test)
test <- cbind(test,NN2_tfidf_test)
test <- cbind(test,knn1_tfidf_test)
test <- cbind(test,knn2_tfidf_test)
test <- cbind(test,knn3_tfidf_test)
test <- cbind(test,knn4_tfidf_test)
test <- cbind(test,knn5_tfidf_test)
test <- cbind(test,knn6_tfidf_test)
test <- cbind(test,knn7_tfidf_test)
test <- cbind(test,knn8_tfidf_test)
test <- cbind(test,knn9_tfidf_test)
test <- cbind(test,knn10_tfidf_test)
test <- cbind(test,knn11_tfidf_test)

test <- cbind(id,test)
for(i in 1:ncol(test)) { test[,i] <- as.character(test[,i])}

write_csv(test,paste0(path,"test_2nd.csv"))
